server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:MyNameIsBigBoy/spring-cloud-config.git #github上仓库地址
          search-paths: #搜索目录
            - springcloud-config
      ##读取分支
      label: master
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据库操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&charactorEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entity   #所有别名类所在的包



eureka:
  client:
    #表示是否将自己注册进EurekaServer默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必循设置为true才能配合Ribbon负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7003/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: config3344
    prfer-ip-address: true